### ISSUE TITLE
PE or Mach-o?

### ISSUE THREAD

**Issue by peasead** [plasma-disassembler/plasma#6]
I'm sure you've been asked many times, but any plans on expanding this to PE or Mach-o?

If you're not looking that way, do you know of similar projects (Python scripts, etc.) that do?

**Comment by joelpx** [comment]
I will look for PE in a first time, maybe a python library already exists to read this format.
In fact, it will not be hard to port to other formats (only the file disassembler.py has to be generic).
Sorry, I don't know similar projects.

**Comment by joelpx** [comment]
I added support for PE. I let the issue opened for an eventually support for Mach-o.

**Comment by peasead** [comment]
Thanks for the quick turn-around.

I added the additional dependency (pefile-py3k), but when I run a PE through I get a pretty nondescript error "symbol main not found". I assume that this may have to do with the fact that there is no symbol resolution for PE yet?

To try and help, I looked around to see what could be missing or if there was anything obvious. I see "symbol main" referenced in "regen.sh". Additionally, "symbol" is in /lib/elf.py, output.py, and pe.py. I'm sorry, I can't be of much help as to what they mean specifically in those files...but I'm sure you already know all of this

**Comment by joelpx** [comment]
Yes there is no symbol resolution for the moment with PE. If no address or symbol is given, by default the tool try to disassemble at the symbol main. The error is normal, I just have to implement some functions in lib/pe.py. For bypassing this error you can give an other address with for -x=0xHEXA_ADDRESS.

**Comment by lunixbochs** [comment]
Maybe worth looking at cle? https://github.com/angr/cle

**Comment by joelpx** [comment]
Interesting ! Thank you, I will take a look.

**Comment by CoolOppo** [comment]
> do you know of similar projects

https://github.com/radare/radare2

radare2 supports some basic pseudo-c decompilation, and they're currently working on radeco to improve the decompilation a lot.

**Comment by joelpx** [comment]
Relocations now uses the same code as CLE
e62998b924ec6fcee83bcc3b6b85a048605cb1ee
